name: Terraform

on:
  workflow_dispatch:
  push:
    branches:
      - 'create_s3_bucket'
  pull_request:

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1

        - name: Terraform Init
      run: terraform init
      working-directory: ./s3_bucket

    - name: Terraform Validate
      run: terraform validate
      working-directory: ./s3_bucket

    - name: Terraform Plan
      run: terraform plan
      working-directory: ./s3_bucket

    - name: Terraform Apply
      run: terraform apply -auto-approve
      working-directory: ./s3_bucket
